status-im/nim-status

.gitignore, Makefile, README.md, nim_status.nimble, src/nim_status.nim, src/status_go.nim, src/types.nim, test/nxjson.c, test/nxjson.h, test/test.c
To test:
```
make update
make
make tests
```
=> feat: build nim_status.a static library and create simple test file in C

Makefile
For example, when static linking is used it's a better test that linking happened and works as expected if `PCRE_LIB_DIR`, etc. aren't added to `LD_LIBRARY_/PATH`.
=> refactor: don't unnecessarily add entries to LD_LIBRARY_/PATH when running tests

.github/workflows/test.yml, .gitmodules, Makefile, nim_status.nimble, nim_status.nims, nim_status/lib/database.nim, nim_status/lib/settings.nim, nim_status/lib/settings/types.nim, nim_status/lib/settings/utils.nim, test/nim/settings.nim
=> feat: settings

nim_status.nimble, nim_status/lib/callrpc.nim, nim_status/lib/conversions.nim, nim_status/lib/settings.nim, nim_status/lib/settings/types.nim, test/nim/callrpc.nim, test/nim/settings.nim
=> feat: pass requests done via callRPC to infura

.github/workflows/test.yml, Makefile, nim_status.nimble, nim_status/lib/conversions.nim, nim_status/lib/database.nim, nim_status/lib/settings.nim, nim_status/lib/settings/types.nim, test/nim/callrpc.nim, test/nim/db_smoke.nim, test/nim/settings.nim
=> feat: make use of updated nim-sqlcipher apis

.gitmodules, nim_status.nimble, nim_status/lib/account.nim, nim_status/lib/account/paths.nim, nim_status/lib/account/types.nim, test/nim/bip32.nim
WIP
@stefantalpalaru:
In this project we have `vendor/nim-secp256k1` and we also have `vendor/nim-waku/vendor/nim-secp256k1`. When doing a `make test-nim`, nimbus-build-system ignores the folder `vendor/nim-secp256k1` and uses the submodule inside `nim-waku/vendor`. Is there a way to force nimbus-build-system to use the top level submodule? (I made a change in https://github.com/status-im/nim-secp256k1/pull/25 that is not being found)
=> feat: bip32

.github/workflows/test.yml, nim_status/lib.nim, nim_status/lib/accounts.nim, nim_status/types.nim, test/nim/accounts.nim
=> Add accounts CRUD

nim_status.nimble, nim_status/lib.nim, nim_status/lib/chats.nim, nim_status/lib/messages.nim, test/nim/chats.nim, test/nim/messages.nim
Fixes #88 
Fixes #89 
TODO: fix failing markMessagesSeen test
=> Messages/Chats CRUD

nim_status.nimble, nim_status/lib.nim, nim_status/lib/permissions.nim, test/nim/permissions.nim
=> feat: dapp permissions CRUD

nim_status/lib/chats.nim, test/nim/chats.nim, test/nim/messages.nim
Fixes #93
Fixes #94 
Includes cherry-picked commit from `feat/contacts`.
=> muteChat, unmuteChat, blockContact

.gitmodules, nim_status.nim, nim_status/c/go/shim.nim, nim_status/c/nim_status.nim, nim_status/go/shim.nim
=> Add support for status-react

.gitmodules, Makefile
Also, clarify comment and pwd usage re: nat-libs-sub target in Makefile.
=> build: remove unneeded nim-nat-traversal in top-level vendor

Makefile, nim_status.nimble, nim_status/client.nim, nim_status/config.nim, nim_status/database.nim, test/client.nim, test/test_all.nim
=> Add StatusConfig

examples/chat.nim, examples/chat/client.nim, examples/chat/client/common.nim, examples/chat/client/events.nim, examples/chat/client/tasks.nim, examples/chat/client/waku_chat2.nim, examples/chat/config.nim, examples/chat/tui/actions.nim, examples/chat/tui/commands.nim, examples/chat/tui/common.nim, examples/chat/tui/screen.nim, nim_status.nimble, test/accounts.nim
=> feat: add join, leave, and topics commands to example client

examples/chat/client/events.nim, examples/chat/client/tasks.nim, examples/chat/tui/actions.nim, examples/chat/tui/commands.nim, examples/chat/tui/screen.nim
=> feat: distinguish messages by waku v2 content topic

examples/chat/client.nim, examples/chat/client/events.nim, examples/chat/client/tasks.nim, examples/chat/tui/actions.nim, examples/chat/tui/commands.nim, examples/chat/tui/common.nim, nim_status/client.nim, nim_status/tokens.nim
=> Custom tokens support in example chat app

examples/client/client.nim, examples/client/client/events.nim, examples/client/client/tasks.nim, examples/client/tui/actions.nim, examples/client/tui/commands.nim, examples/client/tui/common.nim, status/accounts/accounts.nim, status/accounts/generator/generator.nim, status/client.nim, test/accounts/accounts.nim, test/accounts/generator/generator.nim, test/accounts/public_accounts.nim
Closes #225.
Deletes wallet account by wallet index.
Add account db tests for additional account procs: getWalletAccount, getWalletAccounts, and deleteWalletAccount
Add account generator tests for additional generator procs: deleteKeyFile
=> feat: delete wallet account

Makefile
Set INCLUDE/LIB dirs accordingly after detection.
=> build: attempt to detect whether linux distro is based on debian

examples/client/client.nim, examples/client/client/events.nim, examples/client/client/tasks.nim, examples/client/tui/actions.nim, examples/client/tui/commands.nim, examples/client/tui/common.nim, status/api.nim, status/api/opensea.nim
fixes #263 
@michaelsbradleyjr @emizzle if you could help on the review ;) I am new to the repo
=> feat: Integrate with opensea API to fetch collectible

examples/client/tui/actions.nim
=> chore: print an error in the TUI when a nonexistent command is entered

status/private/accounts/accounts.nim
We're already checking `chat = 0` in `getWalletAccounts` (plural), and we should do the same in `getWalletAccount` (singular).
This allows `getWalletAccount` to retrieve the address for the default created account, a.k.a. `Status account`. That address should be usable with e.g. the `/sendtransaction` command.
Also, in SQL statements (and some comments) switch from 0/1 to FALSE/TRUE for boolean columns.
Closes #289.
---
See also: https://github.com/status-im/nim-status/pull/268#discussion_r692363992.
=> fix: in getWalletAccount check `chat = FALSE` instead of `wallet = 0`

examples/client/client.nim, examples/client/client/events.nim, examples/client/client/tasks.nim, examples/client/tui/actions.nim, examples/client/tui/commands.nim, examples/client/tui/common.nim, status/api/common.nim, status/api/opensea.nim, status/api/provider.nim, status/api/tokens.nim, status/private/callrpc.nim, status/private/common.nim, status/private/opensea.nim, status/private/token_prices.nim
Fixes #238.
**Debugging note**: it is important to properly initialise `Table` objects. See https://github.com/status-im/nim-status/blob/307a321e2530d0de904b0b6dc18793e95fe56682/status/api/common.nim#L54.
Otherwise some operations on those objects might crash with `SIGSEGV`s, which is quite difficult to debug (e.g., writing to a `var` works fine, but reading from it causes a crash). Kudos to @michaelsbradleyjr for helping to catch that one.
=> Fetch token prices from cryptocompare.io
