status-im/nim-status

.github/workflows/test.yml
.gitignore
Makefile
nim_status.nimble

See: https://github.com/status-im/nim-sqlcipher/pull/12 and https://github.com/status-im/nim-sqlcipher/pull/22
It is now assumed (and effectively required) that builds of nim-status (and nim-sqlcipher) on Windows will be done in an msys2 environment.

ci: refactor GitHub Actions workflow in same manner as nim-sqlcipher's refactored workflow

---

.github/workflows/test.yml

The workaround is not needed if Go is installed as a package in the msys2 environment.

ci: remove Go version workaround for Windows from GitHub Actions workflow

---

nim_status.nimble
nim_status/lib.nim
nim_status/lib/account.nim
nim_status/types.nim
test/nim/account.nim

Adds the createAccount function to create a random account from  a random private Key.
Returns it as an Account object containing the private key, public key and address.
The function must be called with an `rng` object that should be generated on app start so that it can be reused  avoid using system resources (such as urandom) after that (explanation taken from the nim-eth repo

feat: add createAccount function to create a random account

---

nim_status/lib/settings.nim

Use the Settings type's dbColumnName and dbTableName values in the `createSettings` query instead of hardcoding the names. This allows for changes, is strongly-typed, and prevents errors.

fix: use settings dbColumnName and dbTableName values

---

.github/workflows/chat.yml
.github/workflows/test.yml

See: https://github.com/msys2/MINGW-packages/issues/9010
Also remove a previous workaround re: Rust in MSYS2/MINGW64 on Windows that's no longer necessary.
And cleanup implementation of a workaround re: the `ar` utility on macOS, i.e. do it the same way using an `if..fi` block.

ci: implement workaround re: Rust in MSYS2/MINGW64 on Windows

---

.github/workflows/chat.yml
.github/workflows/test.yml

Using a full matrix of static/shared linking has been useful in the past for catching edge cases, but none have been experienced in recent months so limit to static linking to reduce build and run times in this workflow. The full matrix can always be activated in a PR branch if it's suspected we're bumping into an edge case as experienced previously.

ci: limit to static linking in test workflow in GitHub Actions

---

.github/workflows/chat.yml
.github/workflows/test.yml

It's no longer necessary owing to changes made yesterday by the MSYS2 maintainers/contributors.

ci: remove workaround re: setting RUSTFLAGS env var in Windows

---

examples/chat/client.nim
examples/chat/client/events.nim
examples/chat/client/tasks.nim
examples/chat/task_runner/tasks.nim
examples/chat/task_runner/workers/thread_worker.nim
examples/chat/tui/actions.nim
examples/chat/tui/commands.nim
examples/chat/tui/common.nim
examples/chat/tui/screen.nim
nim_status/account.nim
nim_status/accounts.nim
nim_status/client.nim
nim_status/database.nim
nim_status/mnemonic.nim
nim_status/multiaccount.nim
nim_status/util.nim
test/accounts.nim
test/callrpc.nim
test/chats.nim
test/client.nim
test/contacts.nim
test/mailservers.nim
test/messages.nim
test/multiaccount.nim
test/pendingtxs.nim
test/permissions.nim
test/settings.nim
test/tokens.nim
test/tx_history.nim

Closes: #180.
Closes: #177.
Closes: #184.
Accounts can be created with the `/create` or `/createaccount` command. Existing accounts can be listed with the `/list` or `/listaccounts` command.
Account keyuid is now being generated on the multiaccount.
account.loginTimestamp is now NULL when inserted in the DB, and can be updated using `updateAccount` or `updateAccountTimestamp`.
fix: run migrations only on non-existant DBs
Removes the need to pass in a migration definition file. We do not need to run migrations, unless we are instantiating a DB.

feat: Add create account and list accounts commands

---

examples/chat/client/tasks.nim
examples/chat/tui/tasks.nim
nim_status/multiaccount.nim
test/chats.nim
test/messages.nim
test/mnemonic.nim
test/multiaccount.nim
test/waku_smoke.nim

A few uses remain:
* In `examples/waku_chat2.nim`; that code was copied from nim-waku and is only for reference.
* In `chat/client/tasks.nim`, where the signature of `proc statusContext*(arg: ContextArg)` is intended to match `type Context` of `examples/chat/task_runner/tasks.nim` but we know the argument passed to it is actually of `type StatusArg`.
* In multiple modules within `examples/chat/task_runner/`, where casting plays a role in de/serializing data sent across instances of `AsyncChannel`, and resolving the correct type of worker (thread or pool) per `kind` metatdata tracked as part of worker creation.

refactor: remove unnecessary use of cast in modules within examples

---

examples/chat/client.nim
examples/chat/client/common.nim
examples/chat/client/events.nim
examples/chat/client/tasks.nim
examples/chat/task_runner/macros.nim
examples/chat/task_runner/tasks.nim
examples/chat/task_runner/workers/pool_worker.nim
examples/chat/task_runner/workers/thread_worker.nim
examples/chat/tui/actions.nim
examples/chat/tui/commands.nim
examples/chat/tui/common.nim
examples/chat/tui/screen.nim
examples/chat/tui/tasks.nim
nim_status/accounts.nim
nim_status/client.nim
nim_status/database.nim
nim_status/migrations/accounts/0001_accounts.up.sql
nim_status/migrations/accounts/1606224181_drop_photo_path_from_accounts.down.sql
nim_status/migrations/accounts/1606224181_drop_photo_path_from_accounts.up.sql
test/accounts.nim

feat: add login and logout commands to example client

---

examples/chat/client.nim
examples/chat/client/common.nim
examples/chat/tui/actions.nim
examples/chat/tui/commands.nim
examples/chat/tui/common.nim
examples/chat/tui/macros.nim

Closes #189.
Add support for the `/help` command, which dynamically builds a list of help commands based on the `help()` procs defined for each command type, ie `Login`.
The `help` proc returns a type of `HelpText`, which contains all the information necessary to render help information for that command. It contains the command, parameters (each parameters contains a name and description), aliases, and a description.
The help text is generated (at compile time) by a macro called `buildCommandHelp()`. Once the `/help` command is executed, the output of `buildCommandHelp()` is passed to the task runner so that a `HelpResult` event can be created and the help text can be displayed on screen. Because the text is generated at compile time, it is not necessary to pass this text through the task …

feat: Add help command and help definitions

---

.github/workflows/chat.yml
.github/workflows/test.yml
Makefile

Gives better compatibility at compile and runtime, and notably better performance re: e.g. disk IO.

build: switch from MSYS2 MINGW64 to MSYS2 UCRT64

---

examples/chat/client.nim
examples/chat/client/tasks.nim
examples/chat/tui/commands.nim
examples/chat/tui/common.nim
nim_status/accounts/accounts.nim
nim_status/accounts/generator/generator.nim
nim_status/client.nim
nim_status/conversions.nim
nim_status/pendingtxs.nim
nim_status/settings.nim
nim_status/settings/types.nim
nim_status/tokens.nim
nim_status/tx_history.nim
test/accounts/generator/generator.nim
test/accounts/public_accounts.nim
test/chats.nim
test/client.nim
test/contacts.nim
test/messages.nim
test/multiaccount.nim
test/pendingtxs.nim
test/settings.nim
test/tx_history.nim

Closes: #197.
NOTE: This PR is replacing PR #229 -- somehow that PR was closed automatically when merging #223..
Add funcs to support importing a wallet account via private key.
Support password validation before importing the keystore file. Prevent duplicate keystore files from being imported.
Add keystore file unit tests for storing and loading of key files
Add import wallet pk command to example chat client
Refactor web3_conversions imports to insteaad import `nim_status/conversions`.

feat: support importing wallet accout via private key

---

nim_status/database.nim

Comment out and provide an explanatory comment re: the custom settings that we originally carried over from status-go.
Closes #209.

refactor: use SQLCipher v4 defaults re: algorithms, iterations, etc.

---

examples/chat/client.nim
examples/chat/client/tasks.nim
examples/chat/tui/commands.nim
examples/chat/tui/common.nim
nim_status/accounts/generator/generator.nim
nim_status/client.nim

Closes: #224.
Allows a user to import a wallet account via 12-word mnemonic seed.
The account is first imported in the account generator. Then a wallet account is derived at the root wallet path (m/44'/60’/0’/0/0) from the master key of the mnemonic. This account is then stored in the Accounts table of the user’s db.

feat: import wallet account via mnemonic

---

examples/chat/client.nim
examples/chat/client/tasks.nim
examples/chat/tui/commands.nim
examples/chat/tui/common.nim
nim_status/client.nim

Closes: #226
Add command (`/addwalletwatch`, `/addwatch`) that allows adding a watch-only account to the example client.

feat: Add watch-only wallet account

---

examples/client/tui/actions.nim
examples/client/tui/screen.nim
examples/client/tui/tasks.nim

Note: on mac keyboards the delete key is backspace and on mac laptop keyboards fn+delete is delete ("forward delete"). Some mac keyboards have a separate key, also named delete, for performing forward deletion.
---
After I've tested locally on Linux and Windows, I'll take this PR out of draft.
Tested on:

feat(client): basic support for backspace

---

examples/client/client/common.nim
examples/client/client/events.nim
examples/client/client/tasks.nim
status.nim

There's one remaining import of a non-api (private) module in `examples/client/client/tasks.nim`:
```
../../status/private/protocol
```
That one will be removed in a forthcoming PR that moves import/usage of nim-waku from the example client to the nim-status library itself.

refactor: example client does not import non-api modules of nim-status

---

examples/client/client.nim
examples/client/client/events.nim
examples/client/client/tasks.nim
examples/client/tui/actions.nim
examples/client/tui/commands.nim
examples/client/tui/common.nim
status/api.nim
status/api/common.nim
status/api/provider.nim
status/private/callrpc.nim
status/private/networks.nim
status/private/settings/types.nim
status/private/tx_history.nim
test/callrpc.nim
test/tx_history.nim

Adds a new command `/call` or `/rpc` that receives a json string containing the call being sent to an ethereum provider

feat: add /call command to TUI to execute eth rpc methods

---

examples/client/tui/commands.nim

Also fix `proc help` for `AddWalletWatchOnly`, which was incorrectly using `"addwalletseed"` instead of `"addwalletwatch"`.
Closes #276.

fix: help command should not crash if some commands don't have alias

---

examples/client/client.nim
examples/client/client/events.nim
examples/client/client/serialization.nim
examples/client/client/tasks.nim
examples/client/tui/actions.nim
examples/client/tui/commands.nim
examples/client/tui/common.nim
status/api/provider.nim
status/private/accounts/generator/generator.nim
status/private/callrpc.nim

Example command:
`/trx 0x30575c21a1Ec966Cb06eC9aa3dc697c8dECd0e14 0x0000000000000000000000000000000000000000 0 1 255 10000 0x7f7465737432000000000000000000000000000000000000000000000000000000600057 0 1`
Response from infura:
Receiving this message means that Infura understood the raw transaction that was signed and was able to get the `from` address from the signed transaction.

feat: add /sendtransaction command to TUI

---

examples/client/client.nim
examples/client/client/events.nim
examples/client/client/tasks.nim
examples/client/tui/actions.nim
examples/client/tui/commands.nim
examples/client/tui/common.nim
examples/client/tui/tasks.nim
status/api/networks.nim
status/private/settings.nim
status/private/util.nim
test/api/networks.nim
test/test_all.nim

Closes: #278.
Add `/switchnetwork` command that allows a user to switch their upstream RPC network.
feat: add /listnetworks command (aliased to `/networks`)
Lists all upstream networks from settings.
Also included in this PR is some alphabetical reorganisation.
NOTE: this PR could be squashed before merge.

feat: allow network to be switched
